### ISSUE TITLE
[Suggestion] A couple of suggestions.

### ISSUE THREAD

**Issue by nativepapaya** [Nik-Potokar/XIVComboWayTooAkiiified#1]
1. Dark Knight:

- Would it be possible to apply the overcap feature to dark knight's single target as well, similar to warrior and gunbreaker? There was only one other plugin that did this but it is no longer updated.

2. Warrior

- Changing your 1-2-3 to use Storm's Eye if it is missing is a great idea. The only issue right now is that it seems to only trigger if Storm's Eye is not active, which can lead to situations where it falls of for several GCDs. An alternative would be to check if the duration of Storm's Eye is 15 seconds or less similar to ninja.
- The warrior overcap feature seems to trigger too early, as it triggers fell cleave as soon as you have 50 rage. A cut off of 70 rage or greater would be better as that would ensure you always have 20 rage available for Uphheaval

Thank you!

**Comment by nativepapaya** [comment]
I'm back with another Warrior suggestion. This one is minor but I noticed that the overcap feature only checks if the Storm's Eye/Path will overcap. It would work better if the check was also added to Maim as well, as it also adds beast gauge and sometimes you overcap before getting to the Storms.

**Comment by Nik-Potokar** [comment]
Hey im sorry for the very late reply!

I am currently looking into that but having a few issues so it will take a little longer for that.

But in meantime i managed to fix the Storms Eye on main combo (Storms eye will pop instead of storm's path if  storms eye buff timer is less than 15sec )

Thanks ^^ hopefully i will fix the maim one soon 

Any more suggestions are more than welcome!

**Comment by nativepapaya** [comment]
No worries, don't feel rushed on my behalf. 

The storm eye update is awesome, thank you!

**Comment by Nik-Potokar** [comment]
I've managed to update and a little bit of testing and it seems to be working just fine now. 

* Fixed Icon mismatch on fellcleave/innerbeast
* Added overcap check to Maim 

Please let me know if you find any issues or want anything else to be added

[You can update it Here](https://github.com/Nik-Potokar/XIVComboWayTooAkiiified/releases) 
(Il be adding an automated way for addon updates shortly via custom link repo)

**Comment by nativepapaya** [comment]
Tried the the new update and it is awesome. Thank you!

**Comment by Nik-Potokar** [comment]
Hey thanks!

Regarding the PLD i can look into that later tonight. 

Thanks for all the suggestions so far <3

**Comment by Iaotle** [comment]
For Warrior, can we split up the features for Storm's Path? Having Inner Beast / Fell Cleave automatically swapped into the Storm's Path combo at 70 is a bit strange to me, should be an Overcap Feature?

I also personally prefer it to only show up when you would overcap on Beast Gauge (e.g. when you have >80 gauge for Storm's Path or >90 gauge for Maim), since I'm saving up my gauge for Berserk/Inner Release.
