### ISSUE TITLE
Clarification on naming and repo

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/XIVComboWayTooAkiiified#20]
Since ?yesterday I started seeing the repo getting updated, but the updates not happening in game. Now I notice a "new" mod in the repo called XIVSlothCombo, akso by aki, but with an updated version number.

Am I to believe that this new one, is the same, but with a namechange, and the old "XIVComboWayTooAkiiified" is deprecated?

When changes are made to the XIVComboWayTooAkiiified, when can we expect the changed to be shipped to MyDalamudPlugins where they appear in game?

If I have misunderstood anything, feel free to correct me. Much appreciate the effort put in here.

**Comment by Nik-Potokar** [comment]
So to clarify the question regarding name change. 

Yes I will be changing the name from XivComboWayTooAkiiified to XivSlothCombo since before it was just meant to be for personal use ( aka my friends would request custom features)
But now il be adding more custom combos and custom combos that everyone else wants me to add (requests).

And about the update in-game. I usually update it manually via the repo link once a day. This is due to me just wanting to confirm that stuff is working.

But moving forward when I get more time I will be adding a dev-testing branch repo where you can select and test features sooner than the ones in-game (might break stuff ) 

But for now the name and the manual updates will remain for at least a week until I get everything sorted aka have some free time.

**Comment by sauronshotdogs** [comment]
Thanks for the clarification, explains a lot. So whenever the main repo (the mydalamudplugins one) is updated, that is deployed to the game?

I am loving the work you do, is there a way to buy you a beer or a cup of coffee or something?

**Comment by Nik-Potokar** [comment]
Yes whenever I update the repo (dalamudplugins) one that version gets deployed into the game.

Haha don't worry I'm doing this out of love for the game and love of tinkering around with add-ons. 

Just let me know if there is something you want added/fixed that's more than enough.
<3

**Comment by sauronshotdogs** [comment]
If the need ever arises, let me know at least!

There are some tweaks I'd like, but Ill make some tickets regarding those!

What timeslot and timezone can we usually expect a reply?

**Comment by Nik-Potokar** [comment]
Sure! il be happy to fix/add anything you want just put it in the issues page ^^

I'm from EU (CET time zone) but I try to reply or fix stuff asap when I have time.

Also if you want a direct contact you can always add me on discord Aki#9251 since there I'm available most of the day unless I'm at work or busy irl.

Thanks again <3

**Comment by Iaotle** [comment]
hey I mean I wouldn't mind some [coffee](https://www.paypal.me/iaotle)
