### ISSUE TITLE
With regards to Fixed SageDPSFeature to include Dosis at all levels...

### ISSUE THREAD

**Issue by Genesis-Nova** [Nik-Potokar/XIVComboWayTooAkiiified#32]
Mind you I haven't played sage yet, I was just looking at the code.
Assuming Dosis 1, 2, and 3, are upgraded to their higher levels (1>2, 2>3) 
Would it not be possible trim down a lot of the checks to just check for the status effect(s) and instead of return SGE.Eukrasia; do return OriginalHook(SGE.Eukrasia);? as that should return the original ability (or its upgrades if you're high enough level automatically)

**Comment by damolitionn** [comment]
When you use Eukrasia in game, it gives you the Eukrasia buff and changes Dosis to become Eukrasian Dosis. Using return OriginalHook(SGE.Eukrasia); would work if Eukrasia becomes Eukrasian Dosis. I guess you could do return OriginalHook(SGE.Dosis1) and it'll pull the augmented Dosis but there'd still need to be a way to cast Eukrasia first which is why I put in two checks, one to cast Eukrasia and one to then cast Eukrasian Dosis. I might also be misunderstanding what you're saying because I've been up for nearly 24 hours now.

**Comment by Genesis-Nova** [comment]
I mean Its also possible I'm misunderstanding how it works as I haven't played sage yet, just my thoughts on it. There's nothing wrong with it as is I was just thinking there might be a way to trim it down a little
