### ISSUE TITLE
[Suggestion] WAR Overcap

### ISSUE THREAD

**Issue by Iaotle** [Nik-Potokar/XIVComboWayTooAkiiified#6]
Decided to make another issue for this, for better visibility:

For Warrior, can we split up the features for Storm's Path? Having Inner Beast / Fell Cleave automatically swapped into the Storm's Path combo at 70 is a bit strange to me, should be an Overcap Feature?

I also personally prefer it to only show up when you would overcap on Beast Gauge (e.g. when you have >80 gauge for Storm's Path or >90 gauge for Maim), since I might be saving up my gauge for Berserk/Inner Release window.

**Comment by Nik-Potokar** [comment]
Hey!

I've split the overcap feature into an option(Now it wont auto change unless you tick the option)

For the beastgauge i changed to the values that you asked for but i am unsure if the way i've done it so far is the best for high-end optimization (Needs some testing or a code rewrite which i would he happy to do if you are happy to provide me with bit more details since im not a WAR main)

You can test the changes if you compile or download the TEST plugin below.

I'm also available on Discord Aki#9251 incase you want a direct contact so that we can get you the best feature possible.

[WarTest.zip](https://github.com/Nik-Potokar/XIVComboWayTooAkiiified/files/7564474/WarTest.zip)

**Comment by Iaotle** [comment]
I'm not a WAR main either, just noticed it while playing roulettes. I usually just save up gauge for Inner Release windows, that way I can get 4 of them in.
