### ISSUE TITLE
GNB bulletguage cap increase

### ISSUE THREAD

**Issue by HallwayRaptor** [Nik-Potokar/XIVComboWayTooAkiiified#9]
With EW the bullet guage cap increased to 3 at level 88, so the solid barrel combo should be updated for the overcap protection to happen at 3 rather than 2.

**Comment by Nik-Potokar** [comment]
Hey sorry that i got back to you so late

Should be fixed now (Please use the repo since i update it every day)
`https://raw.githubusercontent.com/Nik-Potokar/MyDalamudPlugins/main/pluginmaster.json`

And if possible post new issues [Here](https://github.com/Nik-Potokar/MyDalamudPlugins)

Also please let me know if anything needs fixing or optimizing/adding
